services:
  - type: web
    name: abhi-signals
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn app:app

    envVars:
      - key: TWELVE_DATA_API_KEY
        sync: false
